name: kidcol
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: 2.1.2
  convex_bottom_bar: 3.2.0
  dio: 5.4.0
  cached_network_image: 3.3.1
  printing: 5.11.1
  pdf: 3.10.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.1
  build_runner: 2.4.8
  isar_generator: 
    git: 
      url: https://github.com/Kiruel/isar
      ref: fix/web_build
      path: packages/isar_generator
  flutter_test: 
    sdk: flutter

isar_generator: 
  git: 
    url: https://github.com/Kiruel/isar
    ref: fix/web_build
    path: packages/isar_generator

flutter: 
  uses-material-design: true

